CREATE DATABASE IF NOT EXISTS admin;

USE admin

CREATE TABLE users_Admin (
  id INT(3) NOT NULL AUTO_INCREMENT,
  name VARCHAR(45) NOT NULL,
  lastName VARCHAR(45) NOT NULL;
  password VARCHAR(255) NOT NULL,
  email VARCHAR(100) NOT NULL,
  PRIMARY KEY(id)
);
